corpRegConfig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('app/', include('registration.urls')),
    path('', include('registration.urls')),
]

handler404 = 'registration.views.page404'
handler500 = 'registration.views.page500'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import re_path as url
from . import views

app_name = 'registration'

urlpatterns = [
    url(r'^registration/$', views.RegisterView.as_view(), name='registration'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^corpmember/$', views.ListCorpMemberView.as_view(), name='list_corpmember'),
    url(r'^corpmember/(?P<pk>[0-9]+)/$', views.UpdateCorpMemberView.as_view(), name='edit_corpmember'),
    url(r'^corpmember/(?P<pk>[0-9]+)/delete/$', views.DeleteCorpMemberView.as_view(), name='delete_corpmember'),
    url(r'^corpmember/register/$', views.CreateCorpMembersView.as_view(), name='create_corpmember'),
    url(r'^$', views.RedirectHomeView.as_view(), name='home'),
]

templates/base.html
<!DOCTYPE html>

<html
  lang="en"
  class="light-style layout-menu-fixed"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="static/custom/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    {% block title %}{% endblock %}

    <meta name="description" content="" />

    {% load static %}

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'custom/img/avatars/6.svg' %}" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{% static 'custom/vendor/fonts/boxicons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'custom/vendor/css/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'custom/vendor/css/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'custom/css/demo.css' %}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'custom/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />
    <!-- Page CSS -->
    {% block css %}{% endblock %}

    <!-- Helpers -->
    <script src="{% static 'custom/vendor/js/helpers.js' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'custom/js/config.js' %}"></script>
  </head>

  <body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="app-brand demo">
            <a href="{% url 'registration:list_corpmember' %}" class="app-brand-link">
              <span class="app-brand-logo demo">
                <img width="25" src="{% static 'custom/img/avatars/6.svg' %}"/>
              </span>
              <span class="app-brand-text demo menu-text fw-bolder ms-2">AwaKopa</span>
            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
              <i class="bx bx-chevron-left bx-sm align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <!-- Dashboard -->
            <li class="menu-item" id="dashboard">
              <a href="/dashboard/" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
              </a>
            </li>
            <!-- Register Corp Member -->
            <li class="menu-item" id="dashboard">
              <a href="{% url 'registration:create_corpmember' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-plus-circle"></i>
                <div data-i18n="Analytics">Register Kopa</div>
              </a>
            </li>
            <!-- View Corp Member -->
            <li class="menu-item" id="dashboard">
              <a href="{% url 'registration:list_corpmember' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-user-circle"></i>
                <div data-i18n="Analytics">My Kopas</div>
              </a>
            </li>
          </ul>
        </aside>
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          <nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="bx bx-menu bx-sm"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">

              <ul class="navbar-nav flex-row align-items-center ms-auto">

                <!-- User -->
                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                  <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                      <img src="{% static 'custom/img/avatars/6.svg' %}" alt class="w-px-40 h-auto rounded-circle" />
                    </div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item" href="#">
                        <div class="d-flex">
                          <div class="flex-shrink-0 me-3">
                            <div class="avatar avatar-online">
                              <img src="{% static 'custom/img/avatars/6.svg' %}" alt class="w-px-40 h-auto rounded-circle" />
                            </div>
                          </div>
                          <div class="flex-grow-1">
                            <span class="fw-semibold d-block">{{request.user.first_name}} {{request.user.last_name}}</span>
                            <small class="text-muted">User</small>
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'registration:logout' %}">
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Log Out</span>
                      </a>
                    </li>
                  </ul>
                </li>
                <!--/ User -->
              </ul>
            </div>
          </nav>

          <!-- / Navbar -->
          
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->
            {% block content %}{% endblock %}
            <!-- / Content -->
            <!-- Footer -->
            <footer class="content-footer footer bg-footer-theme">
                <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                  <div class="mb-2 mb-md-0">
                    ©
                    <script>
                      document.write(new Date().getFullYear());
                    </script>
                    NYSC SPECIAL ICT CDS
                  </div>
                </div>
              </footer>
            <!-- / Footer -->
            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
          
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="{% static 'custom/vendor/libs/jquery/jquery.js' %}"></script>
    <script src="{% static 'custom/vendor/libs/popper/popper.js' %}"></script>
    <script src="{% static 'custom/vendor/js/bootstrap.js' %}"></script>
    <script src="{% static 'custom/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'custom/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Main JS -->
    <script src="{% static 'custom/js/main.js' %}"></script>

    <!-- Page JS -->
    {% block js %}{% endblock %}

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

    <!-- alert message -->
    {% if messages %}
	  {% for message in messages %}
    <script>
      alert('{{ message }}')
    </script>
    {% endfor %}
    {% endif %}
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<html
  lang="en"
  class="light-style customizer-hide"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="static/custom/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>Login</title>

    <meta name="description" content="" />

    {% load static %}
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'custom/img/favicon/favicon.ico' %}" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{% static 'custom/vendor/fonts/boxicons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'custom/vendor/css/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'custom/vendor/css/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'custom/css/demo.css' %}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'custom/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />

    <!-- Page CSS -->
    <!-- Page -->
    <link rel="stylesheet" href="{% static 'custom/vendor/css/pages/page-auth.css' %}" />
    <!-- Helpers -->
    <script src="{% static 'custom/vendor/js/helpers.js' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'custom/js/config.js' %}"></script>
  </head>

  <body>
    <!-- Content -->

    <div class="container-xxl">
      <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
          <!-- Register -->
          <div class="card">
            <div class="card-body">
              <!-- Logo -->
              <div class="app-brand justify-content-center">
                <a href="" class="app-brand-link gap-2">
                  <span class="app-brand-logo demo">
                    <img width="25" src="{% static 'custom/img/avatars/6.svg' %}"/>
                  </span>
                  <span class="app-brand-text demo text-body fw-bolder">AwaKopa</span>
                </a>
              </div>
              <!-- /Logo -->
              <h4 class="mb-2">Welcome to AwaKopa! 👋</h4>
              <p class="mb-4">Please sign-in to your account and start the adventure</p>

              <form id="formAuthentication" class="mb-3" action="" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="username" class="form-label">Username</label>
                  <input
                    type="text"
                    class="form-control"
                    id="username"
                    name="username"
                    placeholder="Enter your username"
                    required
                    autofocus
                  />
                </div>
                <div class="mb-3 form-password-toggle">
                  <div class="d-flex justify-content-between">
                    <label class="form-label" for="password">Password</label>
                  </div>
                  <div class="input-group input-group-merge">
                    <input
                      type="password"
                      id="password"
                      class="form-control"
                      name="password"
                      placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                      aria-describedby="password"
                      required
                    />
                    <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                  </div>
                </div>
                <div class="mb-3">
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="remember-me" required />
                    <label class="form-check-label" for="remember-me"> Remember Me </label>
                  </div>
                </div>
                <div class="mb-3">
                  <button class="btn btn-primary d-grid w-100" type="submit">Sign in</button>
                </div>
              </form>

              <p class="text-center">
                <span>New on our platform?</span>
                <a href="{% url 'registration:registration' %}">
                  <span>Create an account</span>
                </a>
              </p>
            </div>
          </div>
          <!-- /Register -->
        </div>
      </div>
    </div>

    <!-- / Content -->

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="{% static 'custom/vendor/libs/jquery/jquery.js' %}"></script>
    <script src="{% static 'custom/vendor/libs/popper/popper.js' %}"></script>
    <script src="{% static 'custom/vendor/js/bootstrap.js' %}"></script>
    <script src="{% static 'custom/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'custom/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->
    <script src="{% static 'custom/js/main.js' %}"></script>

    <!-- alert message -->
    {% if messages %}
	  {% for message in messages %}
    <script>
      alert('{{ message }}')
    </script>
    {% endfor %}
    {% endif %}

    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>

templates/page404.html
<!DOCTYPE html>

<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->
<html
  lang="en"
  class="light-style"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="../assets/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>oops!</title>

    <meta name="description" content="" />

    {% load static %}

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'custom/img/avatars/6.svg' %}" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{% static 'custom/vendor/fonts/boxicons.css' %}" />

   <!-- Core CSS -->
   <link rel="stylesheet" href="{% static 'custom/vendor/css/core.css' %}" class="template-customizer-core-css" />
   <link rel="stylesheet" href="{% static 'custom/vendor/css/theme-default.css' %}" class="template-customizer-theme-css" />
   <link rel="stylesheet" href="{% static 'custom/css/demo.css' %}" />

   <!-- Vendors CSS -->
   <link rel="stylesheet" href="{% static 'custom/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />
   
   <!-- Page CSS -->
    <!-- Page -->
    <link rel="stylesheet" href="{% static 'custom/vendor/css/pages/page-misc.css' %}" />
    
    <!-- Helpers -->
    <script src="{% static 'custom/vendor/js/helpers.js' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'custom/js/config.js' %}"></script>
  </head>

  <body>
    <!-- Content -->

    <!-- Error -->
    <div class="container-xxl container-p-y">
      <div class="misc-wrapper">
        <h2 class="mb-2 mx-2">Page Not Found :(</h2>
        <p class="mb-4 mx-2">Oops! 😖 The requested URL was not found on this server.</p>
        <a href="{% url 'registration:list_corpmember' %}" class="btn btn-primary">Back to home</a>
        <div class="mt-3">
          <img
            src="{% static 'custom/img/illustrations/page-misc-error-dark.png' %}"
            alt="page-misc-error-light"
            width="500"
            class="img-fluid"
            data-app-dark-img="illustrations/page-misc-error-dark.png"
            data-app-light-img="illustrations/page-misc-error-light.png"
          />
        </div>
      </div>
    </div>
    <!-- /Error -->

    <!-- / Content -->

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="{% static 'custom/vendor/libs/jquery/jquery.js' %}"></script>
    <script src="{% static 'custom/vendor/libs/popper/popper.js' %}"></script>
    <script src="{% static 'custom/vendor/js/bootstrap.js' %}"></script>
    <script src="{% static 'custom/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'custom/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Main JS -->
    <script src="{% static 'custom/js/main.js' %}"></script>

    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>

templates/register.html
<!DOCTYPE html>
<html
  lang="en"
  class="light-style customizer-hide"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="static/custom/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>Register</title>

    <meta name="description" content="" />

    {% load static %}
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'custom/img/favicon/favicon.ico' %}" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{% static 'custom/vendor/fonts/boxicons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'custom/vendor/css/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'custom/vendor/css/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'custom/css/demo.css' %}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'custom/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />

    <!-- Page CSS -->
    <!-- Page -->
    <link rel="stylesheet" href="{% static 'custom/vendor/css/pages/page-auth.css' %}" />
    <!-- Helpers -->
    <script src="{% static 'custom/vendor/js/helpers.js' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'custom/js/config.js' %}"></script>
  </head>

  <body>
    <!-- Content -->

    <div class="container-xxl">
      <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
          <!-- Register Card -->
          <div class="card">
            <div class="card-body">
              <!-- Logo -->
              <div class="app-brand justify-content-center">
                <a href="" class="app-brand-link gap-2">
                  <span class="app-brand-logo demo">
                    <img width="25" src="{% static 'custom/img/avatars/6.svg' %}"/>
                  </span>
                  <span class="app-brand-text demo text-body fw-bolder">AwaKopa</span>
                </a>
              </div>
              <!-- /Logo -->
              <h4 class="mb-2">Adventure starts here 🚀</h4>

              <form id="formAuthentication" class="mb-3" action="{% url 'registration:registration' %}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="username" class="form-label">Username</label>
                  <input 
                    type="text" 
                    class="form-control" 
                    id="username" 
                    name="username" 
                    placeholder="Enter your username" 
                    required
                  />
                </div>
                <div class="mb-3 form-password-toggle">
                  <label class="form-label" for="password">Password</label>
                  <div class="input-group input-group-merge">
                    <input
                      type="password"
                      id="password"
                      class="form-control"
                      name="password"
                      placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                      aria-describedby="password"
                    />
                    <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                  </div>
                </div>

                <div class="mb-3">
                  <div class="form-check">
                    <input 
                      class="form-check-input" 
                      type="checkbox" 
                      id="terms-conditions" 
                      name="terms" 
                      required
                    />
                    <label class="form-check-label" for="terms-conditions">
                      I agree to
                      <a href="javascript:void(0);">privacy policy & terms</a>
                    </label>
                  </div>
                </div>
                <button class="btn btn-primary d-grid w-100">Sign up</button>
              </form>

              <p class="text-center">
                <span>Already have an account?</span>
                <a href="{% url 'registration:login' %}">
                  <span>Sign in instead</span>
                </a>
              </p>
            </div>
          </div>
          <!-- Register Card -->
        </div>
      </div>
    </div>

    <!-- / Content -->

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="{% static 'custom/vendor/libs/jquery/jquery.js' %}"></script>
    <script src="{% static 'custom/vendor/libs/popper/popper.js' %}"></script>
    <script src="{% static 'custom/vendor/js/bootstrap.js' %}"></script>
    <script src="{% static 'custom/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'custom/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->
    <script src="{% static 'custom/js/main.js' %}"></script>

    <!-- alert message -->
    {% if messages %}
	  {% for message in messages %}
    <script>
      alert('{{ message }}')
    </script>
    {% endfor %}
    {% endif %}

    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>

templates/view-corp.html
{% extends 'base.html' %}
{% block title %}
{% block css %}
<link href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" rel="stylesheet"/>
<link href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.bootstrap5.min.css" rel="stylesheet"/>
{% endblock %}
<title>My Kopas</title>
{% endblock %}
{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Home /</span> My Kopas</h4>

  <!-- Hoverable Table rows -->
  <div class="card">
    <h5 class="card-header">My Kopas</h5>
    <div class="table-responsive text-nowrap">
      <table class="table table-hover" id="myTable">
        <thead>
          <tr>
            <th>Name</th>
            <th>State Code</th>
            <th>CallUp No.</th>
            <th>PPA</th>
            <th>Batch</th>
            <th>Stream</th>
            <th>Year</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody class="table-border-bottom-0">
          {% for corper in corp_members %}
          <tr>
            <td><strong>{{corper.name}}</strong></td>
            <td>{{corper.state_code}}</td>
            <td>{{corper.call_up}}</td>
            <td>{{corper.ppa}}</td>
            <td>{{corper.batch.upper}}</td>
            <td>{{corper.stream}}</td>
            <td>{{corper.date_created.year}}</td>
            <td>
              <div class="dropdown">
                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                  <i class="bx bx-dots-vertical-rounded"></i>
                </button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'registration:edit_corpmember' corper.id %}"
                  ><i class="bx bx-edit-alt me-1"></i> Edit</a
                  >
                  <form method="post" action="{% url 'registration:delete_corpmember' corper.id%}" style="display:inline">
                    {% csrf_token %}
                    <button class="dropdown-item" type="submit"><i class="bx bx-trash me-1"></i> Delete</button>
                  </form>
                  <!-- <a class="dropdown-item" href="javascript:void(0);"
                    ><i class="bx bx-trash me-1"></i> Delete</a
                  > -->
                </div>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <!--/ Hoverable Table rows -->

</div>

{% endblock %}
{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
<script>
  $('#myTable').DataTable({
      dom: 'Bfrtip',
      buttons: [
          'excel', 'csv'
      ]
  });
</script>
<script>
  $('#view-corp').addClass('active');
</script>
{% endblock %}